export const SET_SORT_BY = "SET_SORT_BY";

export const SET_KEYWORD = "SET_KEYWORD";

export const ADD_CATEGORY = "ADD_CATEGORY";

export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

export const REMOVE_CATEGORIES = "REMOVE_CATEGORIES";

export const ADD_BRAND = "ADD_BRAND";

export const REMOVE_BRAND = "REMOVE_BRAND";

export const REMOVE_BRANDS = "REMOVE_BRANDS";

export const SET_LESSER_PRICE = "SET_LESSER_PRICE";

export const SET_GREATER_PRICE = "SET_GREATER_PRICE";

export const SET_QUERY_STRING = "SET_QUERY_STRING";

export const REMOVE_FILTERS = "REMOVE_FILTERS";