export const CREATE_NEW_CASH_ORDER = "CREATE_NEW_CASH_ORDER";

export const GET_PAYMENT_SESSION = "GET_PAYMENT_SESSION";

export const GET_ALL_ORDERS = "GET_ALL_ORDERS";

export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID";

export const UPDATE_ORDER_PAY_STATUS = "UPDATE_ORDER_STATUS";

export const UPDATE_ORDER_DELIVERY_STATUS = "UPDATE_ORDER_DELIVERY_STATUS";

export const UPDATE_ORDER_CANCEL_STATUS = "UPDATE_ORDER_CANCEL_STATUS";