export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_MOST_USED_PRODUCTS = "GET_MOST_USED_PRODUCTS";

export const GET_NEWEST_PRODUCTS = "GET_NEWEST_PRODUCTS";

export const CREATE_PRODUCT = "CREATE_PRODUCT";