export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES";

export const GET_SUBCATEGORIES_FOR_SPECIFIC_CATEGORY = "GET_SUBCATEGORIES_FOR_SPECIFIC_CATEGORY";

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";